version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
  build: .
  command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
  entrypoint: ["/entrypoint.sh"]
  volumes:
    - .:/app
  ports:
    - "8000:8000"
  depends_on:
    - db
  environment:
    DB_NAME: blog
    DB_USER: bloguser
    DB_PASSWORD: blogpass
    DB_HOST: db

volumes:
  postgres_data:
